- README.md
- feature-issueTemplate.md
- wikipedia/dom_guinar_email.md
- wikipedia/dom_guinard_email.md
1. Add email from Dominique Guinard regarding WoT Wikipedia
2. Add an issue template that can be used to request features such as a new website, history, etc.
> Two Contributions

- docs/developers/index.html
I would be grateful if you add our Node Generator description on developer's page.
> Add description of Node Generator

- docs/pressrelease-wot-rec.html
Add talking points from TALKING.md, in point form.
Synch up with recent modifications by Michael Lagally to master.
> Rec 2020 press release draft

- README.md
- docs/pressrelease-wot-rec.html
get started on PR to add initial content to press release
> Initial draft of REC 2020 Press release

- docs/getting-started/index.html
rendered version: https://cdn.statically.io/gh/w3c/wot-marketing/gettingStarted/docs/getting-started/index.html
> Update content of getting started

- docs/pressrelease-wot-rec.html
say "applications", remove "abstract", add "(WoT)"
> Update press release figure caption

- docs/pressrelease-wot-rec.html
Rendered version: https://cdn.statically.io/gh/w3c/wot-marketing/sebastian-press-release/docs/pressrelease-wot-rec.html?env=dev
>Interoperability of devices and services for the Internet of Things (IoT) with cloud platforms and services 
at a worldwide scale is a huge challenge.
This sentence appears as the 3rd sentence of the press release and will confuse the reader as it gives the impression that only cloud platforms and services are addressed. We should be more generic here.
> WIP: Press release review

- docs/pressrelease-wot-rec.html
Sorry for late contribution, but I added Panasonic Testimonial to Press Release draft.
> Added Panasonic Testimonial

- docs/pressrelease-wot-rec.html
> Conexxus testimonial

- docs/pressrelease-wot-rec.html
[Preview by staticaly](https://cdn.statically.io/gh/w3c/wot-marketing/apply-alan-comments/docs/pressrelease-wot-rec.html) available
> apply Alan's edits

- docs/pressrelease-wot-rec.html
* "availalble" --> fix
* "•Siemens" --> insert space
> fix: typo and layouting issue

- docs/pressrelease-wot-rec.html
Also broke nav menu at top across multiple lines to make it easier to edit and do diffs on (this does not change how it is rendered by the browser).
> Add Singapore testimonial to press release draft

- docs/pressrelease-wot-rec.html
Update sentence mentioning about Node-RED and Node Generator, based on project leads' feedback.
See issue #50.
> Update Node-RED sentence

- material/wot_explainer_script.md
as discussed in marketing call today, this is a cleaned up script suitable for sharing with the animator, that also lays out some key requirements.
> Cleaned up explainer script

- material/explainer-code-sample/td.jsonld
Fixed a typo and added minimum and maximum for humidity.
> Update explainer TD

- docs/wg/index.html
> feat: update links to recent publications

- docs/_config.yml
- docs/activities/general/index.html
> feat: add task force info and links

- docs/activities/tf-architecture/index.html
- docs/activities/tf-discovery/index.html
- docs/activities/tf-security/index.html
Updates to web content to fill in some of the missing TF descriptions.   These can also serve as a template for other TFs to follow (eventually we want things to look consistent...)
> Descriptions for Architecture, Discovery, and Security TFs

- docs/_config.yml
- docs/_layouts/default.html
- docs/getting-started/index.html
- docs/index.html
* re-order navigation and call "More -> Getting Started" simple "Start"
* remove "Welcome" from navigation
> Navi updates

- docs/activities/general/index.html
as decided in the last marketing call a proposal how to re-structure activities entry page
> feat: restructure general activities entry page

- proposals/media-strategy/README.md
- proposals/media-strategy/relevant-media.md
We had some discussions in #94. There is a lack of media coverage on the Web of Things.
I wrote something down and also added some relevant media. Please take it with a grain of salt. This is not a complete media strategy with all details. 
See this more as a starting point. I don't have the time to get more into details.
> Add media proposal

- docs/documentation/index.html
Adds table of content and links section to Documentation
> Pr 120 followup

- docs/_config.yml
- docs/index.html
- docs/videos/index.html
see https://github.com/w3c/wot-marketing/issues/123
> feat: add videos sub page

- docs/cg/index.html
> Add the information on the WoT Japanese CG to wot-marketing/cg

- docs/_config.yml
would revert the change if it doesn't work...
> make baseurl empty for redirection from the W3C server

- docs/_config_dev.yml
will revert this as well if any problem....
> empty baseurl for _config_dev.yml too

- docs/_config.yml
- docs/_layouts/default.html
- docs/index.html
- docs/videos/index.html
> use absolute_url instead for redirection

- docs/index.html
rationale: "w3c" is another twitter account
> full twitter handle

- docs/404.html
fixes https://github.com/w3c/wot-marketing/issues/139
> feat: add 404 page not found site

- docs/videos/index.html
fixes https://github.com/w3c/wot-marketing/issues/140
> feat: adds alt link to secondary location of the videos/index.html

- videos/WoT-Explainer-Video/WOTMotion.it.vtt
I used the same timings, they should be fine. I tested with windows video player and they look ok. Unfortunately, in some places, they are barely visible cause the video player displays the captions in white.
> Add Italian subtitles

- videos/WoT-Explainer-Video/WOTMotion.it.vtt
> Fix the starting time of the entry 10 in WOTMotion.it.vtt

- videos/WoT-Explainer-Video/WOTMotion.de.vtt
> Fix the starting time of the entry 10 in WOTMotion.de.vtt

- videos/WoT-Explainer-Video/WOTMotion.fr.vtt
> Fix the starting time of the entry 10 in WOTMotion.fr.vtt

- videos/WoT-Explainer-Video/index.html
Note: need to have the video file as "WoT_Final_logo.mp4" locally.
> Create index.html to check the synchronization between the video and captions

- docs/ig/index.html
fix https://github.com/w3c/wot-marketing/issues/161
1st proposal for adding liaisons from https://www.w3.org/2001/11/StdLiaison
> Liaison - Issue 161

- docs/developers/index.html
This PR includes the Java API for Thing Descriptions of WoT (JDTs) tool in the Developers section
> Update index.html with WoT-JTD

- docs/developers/index.html
Adds LinkSmart Thing Directory to developers page.
Closes #174
> Add LinkSmart Thing Directory

- docs/developers/index.html
I have also ordered the implementations a bit to put more conformant implementations to the top
> add wade to implementations

- docs/activities/general/index.html
- docs/index.html
fixes https://github.com/w3c/wot-marketing/issues/198
> feat: add text and link to events

- docs/developers/index.html
Updated with UPM's implementation of the Thing Directory
> Updated index.html

- docs/ig/index.html
fixes https://github.com/w3c/wot-marketing/issues/208
> fix: remove links where there is no detail page

- docs/cg/index.html
fixes https://github.com/w3c/wot-marketing/issues/209
> fix: add DSR link

- docs/developers/index.html
fixes https://github.com/w3c/wot-marketing/issues/210
> docs: create new TDD section

- docs/_config.yml
- docs/cg/index.html
- docs/contact/index.html
- docs/index.html
https://github.com/w3c/wot-marketing/issues/203
> feat: reduce navi and add community information

- docs/activities/general/index.html
fixes https://github.com/w3c/wot-marketing/issues/240
> Update (past) Events

- docs/_layouts/default.html
- docs/cg/index.html
- docs/ig/index.html
- docs/index.html
- docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/238
> refactor: replace flaticons with fontawesome

- docs/contact/index.html
based on https://github.com/w3c/wot-marketing/issues/234#issuecomment-1009926241
fixes https://github.com/w3c/wot-marketing/issues/234
> refactor: redesign contact page

- docs/developers/index.html
add AASX Package Explorer tool to the developer list
> add AASX Package Explorer tool

- docs/activities/general/index.html
fixes https://github.com/w3c/wot-marketing/issues/248
> feat: make appear older entries only on request

- docs/activities/general/index.html
fixes https://github.com/w3c/wot-marketing/issues/250
> feat: add ITU-T Webinar on WoT and Smart Cities on Upcoming Event list

- docs/.gitignore
- docs/activities/general/index.html
Fixes https://github.com/w3c/wot-marketing/issues/246
I have adjusted times of meetings and some links and then beautified table souce html
> Timeplan fixes

- docs/_layouts/default.html
- docs/activities/general/index.html
- docs/activities/tf-architecture/index.html
- docs/activities/tf-discovery/index.html
- docs/activities/tf-marketing/index.html
- docs/activities/tf-scripting/index.html
- docs/activities/tf-security/index.html
- docs/activities/tf-td/index.html
- docs/activities/tf-usecases/index.html
- docs/cg/index.html
- docs/cg/template.html
- docs/developers/index.html
- docs/documentation/index.html
- docs/ig/index.html
- docs/index.html
- docs/wg/index.html
> Add  `target="_blank"` to all external links

- docs/documentation/index.html
- docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/257
> fix: update spec links for recent publications

- docs/ig/index.html
fixes #259 
I have also updated the "from to" text
> Update IG Charter Information

- docs/_config.yml
- docs/activities/tf-marketing/index.html
Fixes #220 
I have also added marketing TF to the list of activities in the drop down
> Marketing TF tasks

- videos/WoT-Explainer-Video/WOTMotion.en.vtt
- videos/WoT-Explainer-Video/WOTMotion.fr.vtt
fixes #150 . They need to put into the YouTube subtitles after the merge
> fix duplication in subtitles

- docs/developers/index.html
@thjaeckle I cannot add you as a reviewer but it would be nice if you can have a look. I have tried to describe ditto WoT integration in a concise way but may not be very accurate. Please ignore the categorization for now since the outcome of #245 will change that
> Add Eclipse ditto based tools

- docs/README.md
This should also trigger Netlify preview, let's see
> Add Netlify Information to Readme

- docs/cg/index.html
- docs/cg/template.html
fixes https://github.com/w3c/wot-marketing/issues/270
> refactor: create one link only to dedicated CG pages

- docs/ig/index.html
- docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/282
> fix: links to task-forces that have been changed due to navigation udates

- docs/activities/meetings/index.html
> fix daylight savings for non-us regions

- docs/activities/events/index.html
I added a information about the 5th WoT Japanese CG Meeting  smart building use cases.
> Add about the 5th WoT Japanese CG Meeting

- docs/README.md
> Add Netlify and Daylight Saving information to readme

- docs/_config.yml
- docs/_layouts/default.html
I have added some negative margins so that the new text doesn't push the page further down. Not sure if this is best practice
> Add edit page button on all pages

- docs/_layouts/default.html
fixes https://github.com/w3c/wot-marketing/issues/299#issuecomment-1097623843
> open GH link in new window/tab

- CODE_OF_CONDUCT.md
- LICENSE.md
This is about points 2 and 3 of #304. I have used the baseline versions with no changes
> Add administrative information

- docs/activities/task-forces/index.html
fixes https://github.com/w3c/wot-marketing/issues/308
> refactor: mention and link main wiki/call

- docs/activities/meetings/index.html
> update call times

- docs/ig/index.html
- docs/wg/index.html
> Add participants relative url

- docs/activities/task-forces/index.html
- docs/activities/task-forces/tf-plugfest/index.html
- docs/ig/index.html
> Plugfest tf page and adjust links

- docs/_layouts/default.html
As requested by the systems team
> Add Matomo script from W3C

- docs/ig/index.html
This TF does not exist anymore
> remove PoC TF

- docs/documentation/index.html
fixes https://github.com/w3c/wot-marketing/issues/338
> add link to discovery explainer

- docs/wg/index.html
TD, Arch, Discovery and Profile
fixes https://github.com/w3c/wot-marketing/issues/366
> update links & information about recent publications

- docs/activities/meetings/index.html
> Swap editors with uc call

- docs/README.md
fixes https://github.com/w3c/wot-marketing/issues/374
> Mention IG contrib to the website

- docs/activities/events/index.html
fixes https://github.com/w3c/wot-marketing/issues/376
fixes https://github.com/w3c/wot-marketing/issues/373
> Updates events with Developer Meeting, March 2023

- docs/activities/events/index.html
> Add tpac 2023 to upcoming events

- docs/_layouts/default.html
fixes https://github.com/w3c/wot-marketing/issues/388
[Preview](https://deploy-preview-391--wot-marketing.netlify.app/)
> aligns footer with w3.org

- docs/activities/meetings/index.html
> Update uc call link

- docs/activities/events/index.html
> Update TPAC Link

- docs/developers/index.html
> Change link of LinkSmart

- docs/developers/index.html
fixes #405 
Also CC @barnstee
https://deploy-preview-414--wot-marketing.netlify.app/developers/
> Add ua edge translator and reorder

- docs/activities/meetings/index.html
TODOs:
* ~~WoT Marketing Zoom link~~
* ~~WoT Architecture Zoom link~~
Removed
* WoT Use Cases
Suspended
* WoT Chairs
* WoT Profiles
fixes https://github.com/w3c/wot-marketing/issues/417
> add Zoom links and mark suspended calls

- docs/cg/index.html
> Add Web Thing Protocol CG to Community Groups page

- docs/developers/index.html
> Online Things section at Developers page

- docs/developers/index.html
as we do for other links as well
> Open Online things page in new window

- docs/activities/meetings/index.html
> Remove highlighting of empty calendar slot

- docs/activities/meetings/index.html
fixes https://github.com/w3c/wot-marketing/issues/431
> Update WebConference Page

- docs/index.html
A single post works when given the specific link but a timeline does not work nor do we have an automatic way to get the latest tweet. We can keep updating this manually, remove the embed and link to the account or remove it entirely.
> Trying different Twitter/X integration

- docs/index.html
To change to https://twitter.com/W3C_WoT/status/1711273035322544406
> Update latest tweet

- docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/442
> New publications for Scripting and Binding Template

- docs/activities/events/index.html
> Adding IIWoT to events page

- docs/activities/meetings/index.html
> Swap security and discovery call slots

- docs/activities/meetings/index.html
fixes https://github.com/w3c/wot-marketing/issues/455
> refactor: use winter time properly

- docs/index.html
Regular check to update the sidebar
> Update Twitter sidebar

- docs/index.html
Embedding https://twitter.com/W3C_WoT/status/1737763113384997056
> Add latest tweet

- README.md
Since we have it now, I have used https://shields.io/badges/mastodon-follow to generate it. Once merged, I will copy it over to other repos.
> Add mastodon badge to readme

- docs/index.html
Trying with https://www.mastofeed.com/ to adjust the colours
> Change mastodon integration

- docs/about/contact/index.html
spotted during the call on 23.01
> Mastodon link on contact

- docs/_layouts/default.html
- docs/about/articles/index.html
- docs/about/contact/index.html
- docs/about/history/index.html
- docs/activities/events/index.html
- docs/activities/meetings/index.html
- docs/activities/task-forces/index.html
- docs/activities/task-forces/tf-architecture/index.html
- docs/activities/task-forces/tf-discovery/index.html
- docs/activities/task-forces/tf-marketing/index.html
- docs/activities/task-forces/tf-plugfest/index.html
- docs/activities/task-forces/tf-scripting/index.html
- docs/activities/task-forces/tf-security/index.html
- docs/activities/task-forces/tf-td/index.html
- docs/activities/task-forces/tf-usecases/index.html
- docs/cg/index.html
- docs/cg/template.html
- docs/developers/index.html
- docs/documentation/index.html
- docs/ig/index.html
- docs/videos/index.html
- docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/473
> refactor: remove target="_blank"

- docs/wg/index.html
for:
* Architecture 
* TD
* Discovery
> fix: update links to latest REC publications

- docs/ig/index.html
to accommodate the rechartering procedure, e.g., the AC Review.
> IG Charter extended till 30 June 2024

- docs/activities/meetings/index.html
fixes https://github.com/w3c/wot-marketing/issues/483
> fix: DST changes - use use summer time

- docs/about/articles/index.html
@mlagally has published an article through Oracle Blog. https://github.com/w3c/wot-marketing/blob/main/Article_Policy.md allows this type of article
> Add oracle article

- docs/activities/meetings/index.html
Question: How should we make clear that we start 30 minutes later?
fixes https://github.com/w3c/wot-marketing/issues/488
> refactor: move Marketing to Thursday

- docs/activities/meetings/index.html
see _tentative_ **confirmed** ~~cancelled~~
> refactor: change style based on event status

- docs/videos/index.html
A simple link to the website and YouTube playlist.
> CG Tutorials link

- docs/ig/index.html
I have renamed the Use Cases TF moderators.
> Update index.html of IG

- docs/developers/index.html
> Adding LMOS and kotlin wot

- README.md
Using https://github.com/w3c/wot/blob/main/README.template.md
> Readme Alignment

- docs/developers/index.html
fixes #515 
fixes #514 
also fixing the link of kotlin-wot
@vigneshvsv your tool was already there but I have updated the link
> Tool Updates

- docs/activities/meetings/index.html
see https://github.com/w3c/wot-marketing/issues/497
> refactor: show tooltip after clicking

- docs/about/articles/index.html
> New Articles

- docs/wg/index.html
> Binding Templates Link Update

- docs/activities/events/index.html
> Events Page Update
