material/explainer-code-sample/README.md, material/explainer-code-sample/example-client.js, material/explainer-code-sample/example-server.js, material/explainer-code-sample/td.jsonld
I refactored the example code leveraging on `wot-servient`. In this way, the code is cleaner, shorter and I think easier to understand. 
Also, I modified the Thing Description to represent a possible soil sensor removing the sprinkler action. I thought it is easier to focus if the Thing does just one thing (pun intended). However, we could re-introduce the sprinkler as a second Web Thing and modify the client example accordingly. 
Finally, I also removed some console log, if the code is meant only to be shown I don't think that info messages are relevant.
=> Simplify explainer video example

docs/activities/general/index.html, docs/activities/tf-usecases/index.html
- Add description of WoT Use Case TF under activities 
- question "Use Case" or "Use Cases"?  when used without "TF", "Use Case" sounds weird, when used WITH "TF" then "Use Case" sounds better as it is being used as an adjective.  I used both...)
- Add a link from the general page
=> Add Use Case TF description

docs/activities/tf-discovery/index.html
Fix some spelling and grammar issues in the Discovery TF description.
=> Fix typos in Discovery TF description

docs/activities/tf-usecases/index.html
Address typos noted by @mlagally in PR https://github.com/w3c/wot-marketing/pull/113
=> Fix typos in Use Case TF description

docs/documentation/index.html
Resructure and revise landing page for "Documentation" subsection of web site.
Done:
- basic grammar fixes
- break up long lines to make diffs more useful
- expand tabs to spaces
To do:
- Section headings
- ToC
- links
=> WIP: Revise web Documentation page

docs/activities/tf-discovery/index.html, docs/activities/tf-scripting/index.html, docs/activities/tf-security/index.html, docs/activities/tf-td/index.html, docs/activities/tf-usecases/index.html, docs/cg/index.html, docs/developers/index.html, docs/documentation/index.html, docs/index.html
Review entire site looking for english fixes.
Some minor tweaks here and there.  Please review the opening paragraph.
In some cases my changes went beyond English, i.e. I noticed the use of "gateway" in the description of Scripting and based on recent discussion added "hub", and also added "orchestration" to the set of applications for scripting.
One thing I did not change was the description of the WoT CG since it seemed copied from the charter, but I also felt it was very long, verbose, and confusing, so at some point we should review it and probably update it.  I also cleaned up a "This group does not publish specifications" note under the CGs (for the Japanese CG it was mixed into the list in an odd way).
=> Web english review

docs/ig/index.html, docs/wg/index.html
This change simplifies navigation and gives credit to TF leads.
=> Webpage: Adding TF info to WG and IG overview pages

proposals/blogProposal.md
Here is the first version of the blog post proposal.
I am not sure about the last part, i.e. acknowledgment. It should be decided together I think. Also, there should be the video link/embed put in there but I am not sure how it is done in the W3C blog.
After putting in the blog, we should also tweet about it.
=> add blog proposal for video

docs/ig/index.html, docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/153
- moves groups icons "before" task forces
- spells task forces everywhere the same 
- "stretch" task forces tables to full width to make it look better
=> Fixes Issue 153

docs/activities/general/index.html, docs/activities/tf-architecture/index.html, docs/activities/tf-discovery/index.html, docs/activities/tf-marketing/index.html, docs/activities/tf-scripting/index.html, docs/activities/tf-security/index.html, docs/activities/tf-td/index.html, docs/activities/tf-usecases/index.html, docs/ig/index.html
I have also changed mention of github to GitHub in all TFs and added Michael McCool as a TD co editor
Some things do not exactly satisfy me:
- There is only my name as TF lead but there is no place to put the names since we do not have a document with co-editors. There are many others who contribute, I am mostly moderating.
- We do not have a deliverable, it looks as if the TF is not doing any work.
I think these are some signs that a CG would be more suitable. In any case, better to have this than nothing but the wiki links.
=> Add marketing TF description

docs/activities/general/index.html
fixes https://github.com/w3c/wot-marketing/issues/227
=> docs: move old events to past and add TestFest in February

docs/activities/general/index.html
The TestFest has been shifted to March, see https://github.com/w3c/wot-testing/issues/206
=> TestFest in March

docs/ig/index.html, docs/wg/index.html
fixes https://github.com/w3c/wot-marketing/issues/264
=> fix: use "Siemens AG" consistently

docs/activities/general/index.html
Move Architecture an hour earlier; it was shown at the wrong time.
=> Correct Calendar - Architecture

docs/developers/index.html
As briefly discussed in today's Scripting Call, this PR adds [`dart_wot`](https://pub.dev/packages/dart_wot) (a Scriping API implementation written in Dart) to the list of implementations on the WoT website.
=> Add `dart_wot` to list of WoT Implementations

docs/activities/meetings/index.html
I don't remember how we were fixing this but this is somewhat tricky. The times of the meetings move of course but we have to adjust the fact the UK, most of Europe, Finland switch between UTC-UTC+1, UTC+1-UTC+2 and UTC+2-UTC+3 respectively. Probably a good idea to mark this PR in the readme to see how to do the change
=> Adjust Daylight Saving

docs/developers/index.html
fixes https://github.com/w3c/wot-marketing/issues/280
I have also reordered the tools to more appropriate categories. I have to remove some info from some tools in order to unify the style but only commented them out. Solution of #245 will allow us to put more information per tool while having the same style.
=> Unify tool information and reorg categories

docs/developers/index.html
I have added a category matrix and a table of tools with the features they cover. This is a draft and not intended to be the final look of the page, the table is very basic for sure. My opinions:
- Doing a table of features blows up the table horizontally. I can reduce the granularity.
- Doing a table was nice to see what features are implemented in which tool. I did it with my knowledge and not looking into tools' source codes.
- It is annoying to assign some projects to a single category and table works better in those cases.
- I think that listing the features is nice but a table like this is not a good design or visualization method. It is too high/long (we cannot do anything about that) and too wide (can be simplified)
Looking forward to what people think
=> Add new tool organization

docs/wg/index.html
As announced on the [WoT WG public mailinglist](https://lists.w3.org/Archives/Public/public-wot-wg/2022Jul/0022.html), the Charter of the WoT WG has been renewed, so the WoT WG page should be also updated with the URL and the start/end dates based on the [new Charter](https://www.w3.org/2022/07/wot-wg-2022.html).
Note that the WG participants need to rejoin the group within 45 days, because the renewed WG operates under the [W3C Patent Policy 2020](https://www.w3.org/Consortium/Patent-Policy-20200915/).
=> update WG Charter dates

docs/developers/index.html
This PR adds the currently usable projects under the SIFIS-Home project (https://github.com/sifis-home and https://www.sifis-home.eu/). They are mostly developed by @lu-zero and @dodomorandi so it would be nice to get a review from them as well
fixes #345
=> Add sifis-home projects to developer related tools

docs/activities/events/index.html, docs/activities/meetings/index.html
I have fixed the times of the meetings to account for the removal of daylight saving. Also, the events page was out of date
=> Timezone fix and events update

docs/README.md
Based on the discussion at https://www.w3.org/2022/12/06-wot-marketing-minutes.html , I have put these in the docs readme. Generally, a CONTRIBUTING.md is used in the root level but that is generally a W3C template (IPR etc.) whereas this is really our TF-specific rules. I am open for putting this in another place but trying to find the minutes is quite annoying so anywhere somewhat easy to find is fine by me.
=> Webpage Contribution rules

docs/index.html
Just want to test if this is a better result. There is only a very small actual change, the rest is just capitalization.
It should fix https://github.com/w3c/wot-marketing/issues/365 but not sure yet.
[Preview](https://deploy-preview-382--wot-marketing.netlify.app/)
=> Change twitter integration

docs/videos/index.html
fixes #361 
However, we should keep the explainer video on the top no matter what other intro video comes later on.
=> Video ordering

docs/_layouts/default.html
Clicking on the icon top right results in the following warning. A small fix for that.
=> fix GitHub editing shortcut using master as branch name

docs/Gemfile.lock, docs/activities/task-forces/tf-architecture/index.html, docs/activities/task-forces/tf-plugfest/index.html, docs/activities/task-forces/tf-scripting/index.html, docs/activities/task-forces/tf-td/index.html, docs/ig/index.html, docs/wg/index.html
fixes #445
I have also changed `Intel` to `Intel Corp.` since that is what is shown at https://www.w3.org/organizations/9829/
=> Align TF leads and Editors

docs/documentation/index.html
We use generic links in the rest of the text instead of dated URIs
Hence I do (and suggest to do) the same for the "Further Reading" section changing 
https://www.w3.org/TR/2020/REC-wot-architecture-20200409/
--> to -->
https://www.w3.org/TR/wot-architecture/
fixes https://github.com/w3c/wot-marketing/issues/375
=> refactor: update documentation page with recent publications

docs/ig/index.html
The [current WoT IG Charter](https://www.w3.org/2021/12/wot-ig-2021.html) has been extended till 31 March 2024 to accommodate the rechartering procedure.
=> extended till 31 Mar 2024

docs/_layouts/default.html
As mentioned in https://github.com/w3c/wot-marketing/issues/461#issuecomment-1864746622, this small PR proposes adding a verification link for Mastodon to the website. This way, the link on our Mastodon profile will have a "verified" checkmark, like so:
This change is not really important, since our account is hosted at the W3C instance anyway, but makes the account look even more "official" ;)
=> Add Mastodon verification link to website header

docs/_layouts/default.html
After the merge of #463, verification has not been working yet due to a small, but critical typo. This PR fixes the issue and should get our account verified :)
=> Fix Mastodon verification link

docs/ig/index.html
The new WoT-IG Charter has been approved and the Call-for-Participation message has been sent out.
So we need to update the WoT-IG page according to the [new IG Charter](https://www.w3.org/2024/04/wot-ig-2024.html).
=> update the WoT-IG page with  the information on the new IG Charter

docs/activities/meetings/index.html
Note: profile call seems to not have a wiki link.
fixes https://github.com/w3c/wot-marketing/issues/493
=> fix profile and chairs call on schedule 
